VideoRentalService/VideoRentalService/Controllers/EnquiryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VideoRentalService.Controllers
{
    public class EnquiryController : Controller
    {       
        // Returns a new Enquiry Form
        [AllowAnonymous]
        public ActionResult New()
        {
            return View();
        }

    }
}

VideoRentalService/VideoRentalService/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoRentalService.Models;

namespace VideoRentalService.Controllers
{
    [Authorize(Roles = RoleName.CanManageMovies)]
    public class RentalsController : Controller
    {
        // Returns a New Rental Form
        public ActionResult New()
        {
            return View();
        }
    }
}

VideoRentalService/VideoRentalService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Video Rental Service</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @{
        if (this.User.IsInRole("CanManageMovies"))
        {
            @Html.Partial("_NavBarStaff");
        }

        else
        {
            @Html.Partial("_NavBar");
        }
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Video Rental Service</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

VideoRentalService/VideoRentalService/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("VRS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                <li>@Html.ActionLink("Contact Us", "New", "Enquiry")</li>
            </ul>

            @Html.Partial("_LoginPartial")
</div>

    </div>
</div>

VideoRentalService/VideoRentalService/Views/Shared/_NavBarStaff.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("VRS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Customers<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Customer List", "Index", "Customers")</li>
                        <li>@Html.ActionLink("New Customer", "New", "Customers")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Movies<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Movie List", "Index", "Movies")</li>
                        <li>@Html.ActionLink("New Movie", "New", "Movies")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Rentals<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
                        <li>@Html.ActionLink("Return Rental", "List", "ReturnRental")</li>
                    </ul>
                </li>

                <li>@Html.ActionLink("Enquiries", "List", "EnquiryManager")</li>
            </ul>

            @Html.Partial("_LoginPartial")
</div>

    </div>
</div>